action_space: 36
algo: ppo
batch_size: 32
buffer_capacity: 1000
clip_param: 0.2
device: cpu
game_name: olympics-curling
gamma: 0.99
load_episode: 1300
load_model: false
load_run: 2
lr: 0.0001
max_episodes: 3000
max_grad_norm: 0.5
model_episode: 0
opponent_load_episode: 1300
opponent_load_run: 3
ppo_update_time: 10
save_interval: 500
seed: 1
state_space: 900
